site_name: DODAS Kubernetes operator
theme:
    name: material
    logo:
        icon: cloud_circle
    palette:
        primary: "Deep Blue"
        accent: "Light Blue"
repo_name: "dodas-ts/dodas-operator"
repo_url: "https://github.com/DODAS-TS/dodas-operator"
