apiVersion: dodas.infn.it/v1alpha1
kind: Infrastructure
metadata:
  name: example-infrastructure
spec:
  name: test
  image: busybox
  cloud:
    host: test
  im:
    host: test2
  template: |
    asdasd
    asdasd
  authFile: |
    asdasd