apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: htcondorwns.dodas.infn.it
spec:
  group: dodas.infn.it
  names:
    kind: HTCondorWN
    listKind: HTCondorWNList
    plural: htcondorwns
    singular: htcondorwn
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: HTCondorWN is the Schema for the htcondorwns API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: HTCondorWNSpec defines the desired state of HTCondorWN
          type: object
        status:
          description: HTCondorWNStatus defines the observed state of HTCondorWN
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
