apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: infrastructures.dodas.infn.it
spec:
  group: dodas.infn.it
  names:
    kind: Infrastructure
    listKind: InfrastructureList
    plural: infrastructures
    singular: infrastructure
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Infrastructure is the Schema for the infrastructures API
      properties:
        apiVersion:
          description:
            "APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
          type: string
        kind:
          description:
            "Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
          type: string
        metadata:
          type: object
        spec:
          description: InfrastructureSpec defines the desired state of Infrastructure
          properties:
            allowrefresh:
              description: TokenRefreshConf ..
              properties:
                client_id:
                  type: string
                client_secret:
                  type: string
                iam_endpoint:
                  type: string
              required:
                - client_id
                - client_secret
                - iam_endpoint
              type: object
            cloud:
              description: CloudAuthFields fields for cloud provider
              properties:
                auth_url:
                  type: string
                auth_version:
                  type: string
                domain:
                  type: string
                host:
                  type: string
                id:
                  type: string
                password:
                  type: string
                service_region:
                  type: string
                tenant:
                  type: string
                type:
                  type: string
                username:
                  type: string
              required:
                - auth_version
                - host
                - id
                - password
                - tenant
                - type
                - username
              type: object
            im:
              description: IMAuthFields fields for cloud provider
              properties:
                host:
                  type: string
                id:
                  type: string
                password:
                  type: string
                token:
                  type: string
                type:
                  type: string
                username:
                  type: string
              required:
                - host
                - id
                - type
              type: object
            image:
              type: string
            name:
              type: string
            template:
              type: string
          required:
            - cloud
            - im
            - image
            - name
            - template
          type: object
        status:
          description: InfrastructureStatus defines the observed state of Infrastructure
          properties:
            error:
              type: string
            infID:
              description: "Dodas infrastructure ID"
              type: string
            status:
              type: string
          required:
            - error
            - infID
            - status
          type: object
      type: object
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
  additionalPrinterColumns:
    - name: InfID
      type: string
      description: Infrastructure ID
      JSONPath: .status.infID
    - name: status
      type: string
      description: deployment status
      JSONPath: .status.status
    - name: error
      type: string
      description: deployment error message
      JSONPath: .status.error
